### PR TITLE
fix: NW.js module is not defined fix.

### LINKED ISSUE #77: ReferenceError: module is not defined when used with node-webkit
`[94867:0820/103228:ERROR:nw_shell.cc(336)] ReferenceError: module is not defined
    at file://node_modules/angular-localforage/dist/angular-localForage.min.js:8:221`

If I prepend this line with 'global.' it works as expected:  

```
module.exports = factory(angular, require('localforage')); // Node/Browserify
```

to

```
global.module.exports = factory(angular, require('localforage')); // Node/Browserify
```

Should it check for module/global.module and use the right one?

### PR DESCRIPTION
**Pull request by bradtaniguchi**
Now the factory assignment for localforage is applied to
`global.modules.exports` instead of `modules.exports` if `module` is
undefined.
`module` is undefined in an NW.js environment (for whatever
reason). So now we check for module and we uses global if `module`
is undefined. Otherwise we proceed as before.

Thank @ashleyhindle for fix.

Fixes #77

### CODE REVIEW

File: dist/angular-localForage.js [hunk 1]
```diff
@@ -14,7 +14,11 @@
       return factory(angular, localforage);
     });
   } else if(typeof exports === 'object' || typeof global === 'object') {
-    module.exports = factory(angular, require('localforage')); // Node/Browserify
+    if(typeof module === 'undefined') {
+      global.module.exports = factory(angular, require('localforage')); // NW.js
+    } else {
+      modules.exports = factory(angular, require('localforage')); // Node/Browserify
```
Comment (scotttrinh) [inline dist/angular-localForage.js]: Typo here. Should be `module.exports` not `modules.exports`.

Comment (bradtaniguchi) [inline dist/angular-localForage.js]: Fixed the typo, but I am not sure what you want me to require on the REPL to check if it imports. 

If it means anything I manually added my updated code to my working project using NW.js and the fix works in NW.js and in-browser. 

Just want to make sure I am doing the right thing here :)

Comment (scotttrinh) [inline dist/angular-localForage.js]: Thanks for fixing the typo!

I just mean do something like this on the command line (assuming macOS or linux):

```bash
$ cd LOCATION_OF_YOUR_FIXED_REPO
$ node
> var localForage = require('.')
```

Assuming it doesn't throw an error after that `require` call, we should be good. If you're still confused, I can do it tonight when I get home from work. To be honest, it might error out since node doesn't have a `LocalStorage` global, but I'm just trying to make sure it still works for Browserify and Electron which use the node-style `module.exports`.

Thanks again for the PR!

Comment (scotttrinh) [inline dist/angular-localForage.js]: Also, it looks like your fix hasn't been pushed to your remote.

From your repo:

```bash
git push
```

Comment (bradtaniguchi) [inline dist/angular-localForage.js]: Pushed my changes with the typo fix

Am I being dumb and missing something? (I am rather new to Nodejs overall) 
Here is what happens when I try to require from the root of my repo:

>brad:angular-localForage$node
>\> var localForage = require('.')
ReferenceError: window is not defined
    at /home/brad/Documents/GitHub/angular-localForage/dist/angular-localForage.js:11:44
    at Object.<anonymous> (/home/brad/Documents/GitHub/angular-localForage/dist/angular-localForage.js:25:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at repl:1:19
> \>

also tried
`var localForage = require('angular-localforage')`
same error message as above.

**Comment by scotttrinh** [comment]
@bradtaniguchi

No worries. I mentioned that it might not be possible to require from node
since it doesn't have LocalStorage or IndexedDB or any of that. I'll test
it in Electron tonight and that should be enough.
